version: '3'

services:
  currency-scheduler:
    container_name: currency-scheduler
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend

networks:
  backend:
    external: true
