version: '3'

services:
  app:
    container_name: currency-api-test
    command: npm run coverage
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - 3004
    ports:
      - 3004:3004
    environment:
      - MONGODB_URL=mongodb://mongo-test:27017/currency
      - JWT_SECRET=secret
      - CLIENT_URL=http://localhost:5000
    links:
      - mongo
    volumes:
      - ./:/usr/src/currency-api
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    container_name: mongo-test
    image: mongo:4.2.1-bionic
    restart: always
    ports:
      - "27018:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
