version: '3'

services:
  mongo:
    volumes:
      - ./data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: currency

  currency-api:
    container_name: currency-api-dev2
    command: yarn dev -L
    volumes:
      - ./:/usr/src/app
      - ignore:/usr/local/apps/myapp/dev/node_modules/
    networks:
      - backend

volumes:
  mongo-data:
    driver: local
  ignore:

networks:
  backend:
    external: true
